title: Dostępność
description: blog o dostępności
author: Mikołaj Rotnicki
remote_theme: jekyll/minima
lang: pl

minima:
  skin: dark
  date_format: "%Y-%m-%d"
  
  social_links:
    twitter: rotnicki
    github:  rotnicki
    facebook: rotnicki
    instagram: rotnicki
    rss: rss

header_pages:
  - about.md
  - contact.md

show_excerpts: true
