title: Dostępność!
description: blog o dostępności
author: Mikołaj Rotnicki
theme: minima

minima:
  date_format: "%Y-%m-%d"
  
  social_links:
    github: rotnicki
    twitter: rotnicki

show_excerpts: true
