title: Dostępność
description: blog o dostępności
author: Mikołaj Rotnicki
# theme: minima
remote_theme: mmistakes/minimal-mistakes

# minima:
#  date_format: "%Y-%m-%d"
  
#  social_links:
#    twitter: jekyllrb
#    github:  jekyll
#    rss: rss

# show_excerpts: true
