title: Dostępność
description: blog o dostępności
author: Mikołaj Rotnicki
theme: minima
lang: pl

minima:
  skin: auto
  date_format: "%Y-%m-%d"
  
#  social_links:
#    twitter: jekyllrb
#    github:  jekyll
#    rss: rss

header_pages:
  - about.md
  - contact.md

show_excerpts: true
