title: Dostępność Cyfrowa to jest to!
description: blog o dostępności
author: Mikołaj Rotnicki
theme: minima
language: pl

minima:
  skin: Dark
  date_format: "%Y-%m-%d"
  
#  social_links:
#    twitter: jekyllrb
#    github:  jekyll
#    rss: rss

show_excerpts: true
