title: Dostępność Polska
description: blog o dostępności
author: Mikołaj Rotnicki
remote_theme: jekyll/minima
lang: pl

minima:
  date_format: "%Y-%m-%d"
  skin: dark
  social_links:
    twitter: rotnicki
    github:  rotnicki
    facebook: rotnicki
    instagram: rotnicki
    rss: rss

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

header_pages:
  - about.md
  - contact.md

show_excerpts: true
