title: Dostępność
description: blog o dostępności
author: Mikołaj Rotnicki
theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: auto

social_links:
  - { platform: instagram,      user_url: "https://www.instagram.com/rotnicki" }

show_excerpts: true
